---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-net-ethertun-com-v1-task
  failurePolicy: Fail
  name: mtask.kb.io
  rules:
  - apiGroups:
    - net.ethertun.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tasks
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-net-ethertun-com-v1-task
  failurePolicy: Fail
  name: vtask.kb.io
  rules:
  - apiGroups:
    - net.ethertun.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tasks
  sideEffects: None
